### ISSUE TITLE
Provide basic and advance Python Package templates

### ISSUE THREAD

**Issue by phxnsharp** [pyansys/ansys-templates#14]
The cookiecutter template gives the user the choice of flit, poetry, or setuptools but provides no guidance. Looking through the existing PyAnsys repositories all three project types are represented. Having a consistent standard for all of PyAnsys has huge benefits:
 - Once customers are familiar with one project, they can easily use or work on a different one
 - Internal Ansys developers can share knowledge and tricks
 - Internal Ansys developers can more easily move between products
 - Less strain on the PyAnsys team, as they do not have to be experts in all three

With the size of Ansys and the legacy codebases, we unfortunately probably cannot just enforce a single build system. However, we can strongly recommend, and make the tools lead developers to the right choice. 

This is a request that the PyAnsys make a strong stance for a single build system and to change the tools to lead the developers to make the right choice.

**Comment by jorgepiloto** [comment]
I think this issue can be closed if @phxnsharp agrees. After merging #18, three different Python Package templates are provided now:

```
ansys-templates list
```

returns:

```
Available templates in ansys-templates are:

pybasic: Create a basic Python Package.
pyansys: Create a PyAnsys Python Package project.
pyansys_advanced: Create an advanced PyAnsys Python Package project.
```

Now, it is possible to add new packages in a simple way. This will help #10 to be completed.

**Comment by jorgepiloto** [comment]
This led to opening #22 and its associated PR in #23.
