### ISSUE TITLE
Missing metadata in pyansys-advanced setup.py file

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/ansys-templates#42]
The current `setup_setuptools.py` template file is missing some metadata. In particular, the fields `author`, `maintainer` and `maintainer-email` are missing:

https://github.com/pyansys/ansys-templates/blob/971eba81d301cc522f29b1fe925bd5340b5d5836/src/ansys/templates/python/pyansys_advanced/%7B%7Bcookiecutter.__project_name_slug%7D%7D/setup_setuptools.py#L5-L22

**Comment by akaszynski** [comment]
Yes, that's important and missing. Use our defaults from https://github.com/pyansys/template/
