### ISSUE TITLE
Enforce EOL character encoding

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/ansys-templates#51]
🐞 **Problem**

From a private discussion with Hiroki Takezawa, he pointed out this issue: rendered projects have LF (Posix) encoding even if these are generated in a Windows machine (CRLF encoding).

I'm not really sure why nobody else complained about before. I guess one possibility is that modern editors/IDEs may hide or deal with this issue in a smart way, but not sure at all...

💡 **Solution**

From [cookiecutter 2.X docs], it is possible to enforce new line character in the `cookiecutter.json` via `_new_lines` variable. However, it is also stated:

> Developers should correctly configure their .gitattributes file to avoid line-end character overwrite by git.

I guess we can always add this last file in the rendered template, it will be the simplest solution.

**Comment by greschd** [comment]
> I'm not really sure why nobody else complained about before.

One possible explanation/workaround: If you've got `git` configured with `core.autocrlf = true`, as soon as you clone afresh, you get the correct line endings.

**Comment by jorgepiloto** [comment]
Thanks for the reply! Already shared this with Hiroki, waiting for his feedback on this.

**Comment by greschd** [comment]
Btw, I still think it would be better to generate with system-aware line endings and set the equivalent of `core.autocrlf = true` in `.gitattributes`, as you suggested above.

**Comment by jorgepiloto** [comment]
I just saw this approach in the PyFluent repo, see https://github.com/pyansys/pyfluent/pull/389
