### ISSUE TITLE
Add template for REST client library

### ISSUE THREAD

**Issue by da1910** [pyansys/ansys-templates#80]
We have nice templates for a bunch of API servers, but none for API clients.

Consider leveraging the work in https://github.com/pyansys/openapi-common and the sketch at https://github.com/pyansys/template-openapi to make standard clients in a repeatable way.

**Comment by jorgepiloto** [comment]
Thanks for opening this @da1910!

**Comment by da1910** [comment]
I have an initial draft which I will push to a branch for testing.
