### ISSUE TITLE
Add GIF of usage

### ISSUE THREAD

**Issue by akaszynski** [pyansys/ansys-templates#83]
Would be cool for demo purposes if we had a 10 second GIF showing the usage of this tool.

**Comment by jorgepiloto** [comment]
Solved this in [here]. However, I think it is better if we wait till #85 gets merged so the GIF is up to date with the available list of templates.

[here]: https://github.com/pyansys/ansys-templates/blob/feat/usage_gif/doc/source/_static/usage.gif

**Comment by jorgepiloto** [comment]
Now that #85 got merged, this is being addressed in #104.
